---
services:
  - name: gbdb-service
    id: acb56d7c-sdsad2-vd434-3dfsfa-feb140a59a66
    description: Greenplum data service.
    tags:
      - psql
      - gpdb
    requires:
      - route_forwarding
    bindable: true
    instances_retrievable: 'true'
    bindings_retrievable: 'true'
    metadata:
      provider:
        name: Greenplum database
      listing:
        imageUrl: http://example.com/cat.gif
        blurb: Add a blurb here
        longDescription: A long time ago, in a galaxy far far away...
      displayName: GBDB Service broker
    plan_updateable: true
    plans:
      - name: plan-1
        id: d3031751-XXXX-XXXX-XXXX-a42377d3320e
        description: Some description about plan.
        free: false
        metadata:
          max_storage_tb: 5
          costs:
            - amount:
                usd: 99
              unit: MONTHLY
            - amount:
                usd: 0.99
              unit: 1GB of messages over 20GB
          bullets:
            - Shared fake server
            - 5 TB storage
            - 40 concurrent connections
        schemas:
          service_instance:
            create:
              parameters:
                "$schema": http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  billing-account:
                    description: Billing account number used to charge use of shared fake server.
                    type: string
            update:
              parameters:
                "$schema": http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  billing-account:
                    description: Billing account number used to charge use of shared fake server.
                    type: string
          service_binding:
            create:
              parameters:
                "$schema": http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  billing-account:
                    description: Billing account number used to charge use of shared fake
                      server.
                    type: string